AB string
noiceee/codeChef pull request #9
Opened 2023-08-22 13:11 UTC by ranshu1601

2023-08-22 15:18 UTC, noiceee commented on anshu/abdulBari/string/compareStr.cpp
What is this function trying to achieve?

2023-08-22 15:26 UTC, ranshu1601 commented on anshu/abdulBari/string/compareStr.cpp
this function is comparing two strings and printing the common substring .

2023-08-22 15:27 UTC, noiceee requested changes

2023-08-22 15:27 UTC, noiceee commented on anshu/abdulBari/string/countVowels.cpp
This code needs to be cleaned, do not put so many conditions inside the if statement, instead create an array containing the vowels, and then check if your element is in the array or not, and proceed accordingly. It is a much clear practice.

2023-08-22 15:27 UTC, noiceee commented on anshu/abdulBari/string/findDuplicate.cpp
Do not give outputs from the function itself, instead return an array from the function, and print the elements using a display function in your main function

2023-08-22 15:27 UTC, noiceee commented on anshu/abdulBari/string/plaindrome.cpp
Same here, your function should be generic, and not write to the output stream, instead it should return a value, and using that value, the desired output will be generated in the main function. Also, your output should mention if it's a palindrome or not, and not simple true false

2023-08-22 15:27 UTC, noiceee commented on anshu/abdulBari/string/reverseWord.cpp
Same here, you should avoid void functions, and only use them if you are modifying the contents of an object permanently.

2023-08-22 15:27 UTC, noiceee commented on checks.json
Add this file in gitignore, baar baar ajata hai

2023-08-22 15:27 UTC, noiceee commented on anshu/abdulBari/string/validStr.cpp
Take input from the user, and give better outputs stating the answer and not 0 or 1

2023-08-22 15:27 UTC, noiceee commented on anshu/abdulBari/string/anagram.cpp
For all code, input should be taken from the user, and functions should return a value, using which the output will be generated in the main function. The output should be self-explanatory and not like 0 1 and all.

2023-08-22 15:32 UTC, ranshu1601 commented on anshu/abdulBari/string/countVowels.cpp
okay , as of now just merge .

2023-08-22 15:38 UTC, ranshu1601 commented on checks.json
just check now

2023-08-22 15:39 UTC, ranshu1601 commented on anshu/abdulBari/string/validStr.cpp
Will keep that in mind , tq

2023-08-22 16:58 UTC, noiceee commented on anshu/abdulBari/string/countVowels.cpp
Ee wala krdo

2023-08-23 18:17 UTC, noiceee commented
Please do that vowel one with array

2023-08-23 18:18 UTC, merged

2023-08-23 20:17 UTC, ranshu1601 commented on anshu/abdulBari/string/countVowels.cpp
krta